### ISSUE TITLE
Implement group_by function

### ISSUE THREAD

**Issue by Attrash-Islam** [Attrash-Islam/rudash#35]

**Comment by benbakhar** [comment]
would love to take this one

**Comment by Attrash-Islam** [comment]
Hi Ben and thanks for reaching out.

Some notes to be aware of:

- You must be aligned to the Lodash behavior as much as possible (I try the cases in the console of lodash website).

- You must write some cases in a unit test file that cover as much cases as possible.

- Important to note that you can use already existed implementation that have done, which means that you can use R_.filter because it's already implemented. You can access Rudash functions by referring to `self` in your method.

- Please update the README from Lodash website while changing tiny things like: "Object" becomes "Hash", etc.

- Remember that all Rudash functions are aligned with Ruby community style guidelines, which means that "isNil" becomes "is_nil?", and "groupBy" will be "group_by".

- Perfect PR should look like this one: #74

**Comment by benbakhar** [comment]
#74

**Comment by benbakhar** [comment]
#74

**Comment by Attrash-Islam** [comment]
Merged in `2.11.0`
