### ISSUE TITLE
Fix the PR number in README

### ISSUE THREAD

**Issue by Attrash-Islam** [Attrash-Islam/rudash#81]
We need to fix the link of #73 PR in the README file (The one that is highlighted below in the attached image).

![image](https://user-images.githubusercontent.com/7091543/66686653-d123c300-ec88-11e9-957b-67dba9e7dfd2.png)

**Comment by whattrash** [comment]
I can fix this one!

**Comment by Attrash-Islam** [comment]
Hi @whattrash and thanks for this spirit! Go ahead 💪
