### ISSUE TITLE
Add link to Lodash Website in README

### ISSUE THREAD

**Issue by Attrash-Islam** [Attrash-Islam/rudash#87]
We want to add a link to the highlighted text below that redirects to the Lodash official documentation.

![Screenshot_20191012-153950_Chrome](https://user-images.githubusercontent.com/7091543/66701621-b6902f00-ed06-11e9-916e-08b86384d165.jpg)

**Comment by daningenthron** [comment]
Hi, I can set this up if still needed?

**Comment by Attrash-Islam** [comment]
Sure thing @daningenthron !
