### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by thegedge** [Attrash-Islam/rudash#91]
Hey, @Attrash-Islam. When working on https://github.com/Attrash-Islam/rudash/pull/90 I came up with various suggestions that I think would greatly improve this project:

- [x] Follow the rest of the Ruby community by enforcing a common style (https://github.com/rubocop-hq/ruby-style-guide). If you decide that you don't want to do this, it would still be good to provide a rubocop style file for the style you wish this project to have.
- [ ] Prefer using YARD for API documentation instead of `README`. Note how https://rubydoc.info/gems/rudash is pretty bare. This not only provides documentation that is typical in the Ruby community, but we could also move most (maybe all?) of the test cases into YARD documentation examples (which can be tested).
- [x] I used `take` as an example to implement `drop_right` in https://github.com/Attrash-Islam/rudash/pull/90. In doing so, I ended up with `*rest_args`, but I think both of these should probably just have two arguments (`array, n = 1`). I think anywhere where variable arguments aren't needed, we should be using explicit positional arguments.
- [x] Add various badges (license, link to ruby gems, CI status, and so on) to the top of `README`.
- [x] Have a `lib/rudash/version.rb` file and reference that in your gemspec.
- [x] It's common to have a `Gemfile` and support `bundle exec rake test`.
- [x] Move the contribution guidelines into a `CONTRIBUTING.md` file (https://help.github.com/en/articles/setting-guidelines-for-repository-contributors)

It was easier to put these all into a single issue, so feel free to break it up into smaller issues for anything you'd like to do 🙂

**Comment by Attrash-Islam** [comment]
Will review your suggestions soon!! Thanks a lot ❤

**Comment by Attrash-Islam** [comment]
Already started to fix things thanks to your notes 🙏

Regards the **`*rest_args`** I use them in order to keep align with the Lodash API 🤷‍♂(The dynamic nature of Lodash and JavaScript into the Ruby world).. This is a thing that I like to bring on into the table of Rudash and already done something really nice here ([Dynamic Args Count](https://github.com/Attrash-Islam/rudash/blob/master/lib/utils/dynamic_args_count.rb))

**Comment by Attrash-Islam** [comment]
@thegedge Fixed 1800 rubocop linting errors 😂😅

**Comment by thegedge** [comment]
Nice! I'm pretty busy these days, so not a lot of time to help out, but if you want someone to review code, feel free to add me to any PRs 🙂

**Comment by Attrash-Islam** [comment]
Thanks @thegedge! You already done a huge contribution to the library! 🌹
